apiVersion: apps/v1
kind: Deployment
metadata:
  name: anrs
spec:
  replicas: 7
  selector:
    matchLabels:
      app: anrs
  template:
    metadata:
      labels:
        app: anrs
    spec:
      containers:
      - name: anrs-container
        image: anrs125/sample-private:1.0.1  # This will be replaced dynamically
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred  # Reference the Kubernetes secret
